import type { Status } from './Status';

export type Website = {
  id: string;
  domainName: string;
  accountId: string;
  accountSource: string;
  subscriptionId: string;
  shopperId: string;
  customerId: string;
  resellerId: number;
  ventureId: string;
  type: string;
  homepageId: string;
  createDate: string;
  updateDate: string;
  status: 'active' | string;
  properties: WebsiteProperties;
  options: WebsiteOptions;
  data: WebsiteData;
  // webhooks: { 'after:publish': [Array] },
  planType: 'freemiumV1' | string;
  entitlements: WebsiteEntitlements;
};

export type WebsiteProperties = {
  accountCreationIsc: string;
  accountCreationItc: string;
  accountCreationListingId: string;
  accountCreationTrialLength: string;
  blogStatus: Status;
  businessCategory: string;
  businessName: 'free' | string;
  colorPack: string;
  colorPackCategory: string;
  contactsStatus: Status;
  dpsSubdomain: string;
  editorFirstVisitMarketCookie: string;
  editorFirstVisitUtcDateTime: string;
  editorLastMarketCookie: string;
  editorLastVisitUtcDateTime: string;
  email: string;
  fontPack: string;
  olsAccountStatus: 'ACTIVE' | string;
  olsStatus: Status;
  olaStatus: Status;

  olaLocale?: string;
  olsCurrency?: string;
  olsFirstProductCreated?: string;
  olsLocale?: string;
  olsMarketplaces?: boolean;

  onboardedColorPack: string;
  onboardedFontPack: string;
  onboardedTemplateType: string;
  onboardedTheme: string;
  onboardedVertical: string;
  onboardingCompletedUtcDateTime: string;
  pathway: string;
  themePreset: string;
  ventureId: string;
  virtualOrderId: string;
  publishStatus: string;
};

export type WebsiteOptions = {
  anyoneHasAccess: boolean;
  areSubscribersContacts: boolean;
  cookieBannerDeclineEnabled: boolean;
  cookieBannerEnabled: boolean;
  createdAsNru: boolean;
  membershipAccountsOn: boolean;
  startedAsFreemium: boolean;
  startedAsTrial: boolean;
  usedFontBlacklist: boolean;
  usedHeaderImages: boolean;
};

export type WebsiteData = {
  customerIntentions: {
    getNoticed: boolean;
    localCustomers: boolean;
    onlineStore: boolean;
    onlineAppointments: boolean;
  };
  defaultImageUrls: string[];
  navigation: string[];
  persistentEntitlements: {
    appointments: boolean;
    commerce: boolean;
  };
  productEntitlements: {
    gem: string;
    ssl: boolean;
    getFound: boolean;
    onlineBookkeeping: boolean;
    businessSections: boolean;
    socialMediaManager: boolean;
    cdn: boolean;
    commerce: boolean;
    payments: boolean;
    ads: boolean;
    reservations: boolean;
    ordering: boolean;
    seo: boolean;
    mls: boolean;
  };
  stockImages: {
    url: string;
    lastModified: string;
  }[];
  stockPhotos: [];
  verticalGroups: [];
};

export type WebsiteEntitlements = {
  current: {
    'gem': string;
    'ssl': boolean;
    'getFound': boolean;
    'onlineBookkeeping': boolean;
    'businessSections': boolean;
    'socialMediaManager': boolean;
    'cdn': boolean;
    'commerce': boolean;
    'payments': boolean;
    'ads': boolean;
    'reservations': boolean;
    'ordering': boolean;
    'seo': boolean;
    'mls': boolean;
    'adCredits': boolean;
    'appointments': boolean;
    'appointments.c1SmsNotifications': boolean;
    'appointments.c2EmailReminders': boolean;
    'appointments.c2Rescheduling': boolean;
    'appointments.c2SmsNotifications': boolean;
    'appointments.c2SmsReminders': boolean;
    'appointments.calendarSync': boolean;
    'appointments.facebookBooking': boolean;
    'appointments.onlinePayments': boolean;
    'appointments.recurringEvents': boolean;
    'appointments.singleEvents': boolean;
    'audio': boolean;
    'blog': boolean;
    'coaching': boolean;
    'commerce.checkout': boolean;
    'commerce.instantProvision': boolean;
    'commerce.marketplace': boolean;
    'commerce.productLimit': string;
    'commerce.sms': boolean;
    'contacts': boolean;
    'conversations': boolean;
    'dify.brandGuide': boolean;
    'dify.emailRequests': boolean;
    'dify.ongoingEmails': boolean;
    'dify.ongoingSocialPosts': boolean;
    'dify.reputationManagement': boolean;
    'dify.websiteCare.mwp': boolean;
    'difyPhotoshoot': boolean;
    'dify.contentRequests': boolean;
    'dify.websiteBuild': boolean;
    'dify.websiteCare': boolean;
    'fileUpload': boolean;
    'gallery': boolean;
    'giftcard': boolean;
    'gofundme': boolean;
    'imprint': boolean;
    'insight': boolean;
    'insight.goals': boolean;
    'insight.metrics': boolean;
    'insight.nextSteps': boolean;
    'insight.suggestions': boolean;
    'mcc.ordersPerMonth': boolean;
    'multiPage': boolean;
    'over': string;
    'paymentMethods.paypalForPartners.additionalRate': string;
    'policy': boolean;
    'presenceIQ': boolean;
    'promoType': boolean;
    'pwa': boolean;
    'reviews': boolean;
    'rss': boolean;
    'seo.dify': boolean;
    'seo.siteAudit': boolean;
    'seo.siteAudit.dify': boolean;
    'singlePageHackathon': boolean;
    'socialAds': boolean;
    'socialAds.dify': boolean;
    'socialMediaManager.difySocial': boolean;
    'socialMediaManager.fb': boolean;
    'socialMediaManager.fb.connect': boolean;
    'socialMediaManager.fb.connect.dify': boolean;
    'socialMediaManager.fb.connect.msh': boolean;
    'socialMediaManager.gmb': boolean;
    'socialMediaManager.gmb.connect': boolean;
    'socialMediaManager.gmb.connect.dify': boolean;
    'socialMediaManager.gmb.create': boolean;
    'socialMediaManager.gmb.create.dify': boolean;
    'socialMediaManager.gmb.description': boolean;
    'socialMediaManager.gmb.dqVerification': boolean;
    'socialMediaManager.gmb.hours': boolean;
    'socialMediaManager.gmb.insights': boolean;
    'socialMediaManager.gmb.photos': boolean;
    'socialMediaManager.gmb.post': boolean;
    'socialMediaManager.gmb.reviews': boolean;
    'socialMediaManager.instagram': boolean;
    'socialMediaManager.twitter': boolean;
    'socialMediaManager.twitter.connect.dify': boolean;
    'socialMediaManager.twitter.connect.msh': boolean;
    'socialMediaManager.yelp': boolean;
    'socialMediaManager.yelp.connect': boolean;
    'socialMediaManager.yelp.connect.dify': boolean;
    'socialMediaManager.yelp.create': boolean;
    'socialMediaManager.yelp.create.dify': boolean;
    'terms': boolean;
    'transitions': boolean;
    'video': boolean;
    'website': string;
    'zillow': boolean;
  };
  transitionable: {
    'dify.contentRequests': WebsiteEntitlementsTransitionable;
    'dify.websiteCare': WebsiteEntitlementsTransitionable;
    'seo.dify': WebsiteEntitlementsTransitionable;
    'seo.siteAudit.dify': WebsiteEntitlementsTransitionable;
    'socialAds.dify': WebsiteEntitlementsTransitionable;
    'socialMediaManager.fb.connect.dify': WebsiteEntitlementsTransitionable;
    'socialMediaManager.twitter.connect.dify': WebsiteEntitlementsTransitionable;
  };
};

type WebsiteEntitlementsTransitionable = {
  businessPlusServices1: boolean;
  commerceServices1: boolean;
};
